### ISSUE TITLE
package versioning - see https://github.com/AArnott/Nerdbank.GitVersioning

### ISSUE THREAD

**Issue by djnicholson** [ngdseattle/neo-visual-devtracker#19]

**Comment by devhawk** [comment]
I did this as part of commit [8e3ab56646c7cdf109e5449ddaa40d7faa95cd8b](https://github.com/ngdseattle/neo-visual-devtracker/commit/8e3ab56646c7cdf109e5449ddaa40d7faa95cd8b)
