### ISSUE TITLE
Show unspent transaction info in Address Detail

### ISSUE THREAD

**Issue by devhawk** [ngdseattle/neo-visual-devtracker#24]
Address Detail page shows balances only. While transaction specifics can be hidden by default, the page should allow the user to see all the information returned by [getunspents](https://docs.neo.org/docs/en-us/reference/rpc/latest-version/api/getunspents.html).

For developer scenarios, the tracker needs to be able to copy specific details of a specific unspents transaction as JSON to the clipboard. The next version of the debugger can accept UTXO inputs for transaction invocations in the same JSON format that getunspents uses.

**Comment by djnicholson** [comment]
a760ef474f020d486312791a879103d74b3a479a
